
# --- Base Stage --- 
FROM node:20-alpine AS base
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
# ------------------ 

# --- Development Stage ---
FROM base AS dev
ENV NODE_ENV=Development
WORKDIR /app
# Mount all files for hot-reloading
COPY . . 
EXPOSE 3000

# Start Development Server
CMD ["yarn", "start"]
# ------------------

# --- Production Stage ---
FROM base AS build
ENV NODE_ENV=production
WORKDIR /app
COPY . .
RUN yarn build

# --- Production Stage ---
FROM node:20-alpine AS serve
WORKDIR /app
COPY --from=build /app/build /app/build
RUN yarn global add serve
EXPOSE 3000
CMD ["serve", "-s", "build"]
